mesosMaster: 10.0.2.15:5050
checkpoint: false
frameworkFailoverTimeout: 43200000
frameworkName: MyriadAlpha
frameworkRole: 
frameworkUser: hduser #user the framework runs as
frameworkSuperUser: root #To be depriated, currently permissions need set by a superuser due to Mesos 1760.  Must be root
                         #or have passwordless sudo, if not set will default to the user executing the scheduler.
nativeLibrary: /usr/local/lib/libmesos.so
zkServers: localhost:2181
zkTimeout: 20000
restApiPort: 8192
profiles:
  small:
    cpu: 1
    mem: 1100
  medium:
    cpu: 2
    mem: 2048
  large:
    cpu: 4
    mem: 4096
rebalancer: false
nodemanager:
  jvmMaxMemoryMB: 1024
  cpus: 0.2
  cgroups: false
executor:
  jvmMaxMemoryMB: 256
  path: file:///usr/local/libexec/mesos/myriad-executor-0.0.1.jar
  #The following should be used for a remotely distributed URI
  #nodeManagerUri: hdfs:///namenode:port/dist/hadoop-2.5.0.tar.gz
  #path: hadoop-2.5.0/share/hadoop/yarn/myriad-executor-0.0.1.jar #relative path if nodeManagerUri is set
yarnEnvironment:
  YARN_HOME: /usr/local/hadoop
  #YARN_HOME: hadoop #this should be relative if nodeManagerUri is set
  #JAVA_HOME: /usr/lib/jvm/java-default #System dependent, but sometimes necessary