mesosMaster: localhost:5050
checkpoint: false
frameworkFailoverTimeout: 43200000
frameworkName: MyriadAlpha
frameworkRole: 
nativeLibrary: /usr/local/lib/libmesos.so
zkServers: localhost:2181
zkTimeout: 20000
restApiPort: 8192
profiles:
  small:
    cpu: 1
    mem: 1100
  medium:
    cpu: 2
    mem: 2048
  large:
    cpu: 4
    mem: 4096
rebalancer: false
nodemanager:
  jvmMaxMemoryMB: 1024
  user: hduser
  #group:hadoop #only relevant if remoteDistribution is true
  cpus: 0.2
  cgroups: false
executor:
  jvmMaxMemoryMB: 256
  path: file://localhost/usr/local/libexec/mesos/myriad-executor-0.0.1.jar
  #The following should be uncommented if using a remotely distributed URI
  #remoteDistribution: true
  #nodeManagerUri: file:///opt/hadoop-2.5.0.tar.gz
  #command: myriad-executor-0.0.1.jar
yarnEnvironment:
  YARN_HOME: /opt/hadoop-2.5.0  
  #YARN_HOME: hadoop-2.5.0 #this should be relative if remoteDistribution is set to true